# Generated by Django 3.1.6 on 2021-03-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_to_one', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='mail',
        ),
        migrations.AddField(
            model_name='details',
            name='hallticket',
            field=models.IntegerField(default=True, max_length=10),
        ),
    ]
