# Generated by Django 3.1.6 on 2021-03-06 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one_to_one', '0002_auto_20210305_2120'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='Exam_Details',
        ),
    ]
