# Generated by Django 3.1.6 on 2021-03-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eno', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=20)),
                ('esal', models.FloatField()),
                ('eemail', models.EmailField(max_length=50, unique=True)),
            ],
        ),
    ]
