# Generated by Django 3.1.6 on 2021-03-05 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Projects.employee')),
                ('city', models.CharField(default=False, max_length=20)),
                ('dept_name', models.CharField(default=False, max_length=30)),
            ],
        ),
    ]
